# Generated by Django 6.0.2 on 2026-02-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_publication_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='hora_creacion',
            new_name='fecha_publicacion',
        ),
    ]
